03-SYMFONY/actunews/src/Entity/User.php
<?php

namespace App\Entity;

use ApiPlatform\Metadata\Put;
use ApiPlatform\Metadata\Delete;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\UserRepository;
use App\Controller\Api\MeController;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\GetCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
#[ApiResource(
    operations: [
        new GetCollection(
            uriTemplate: '/me',
            controller: MeController::class,
            //security: "is_granted('USER_VIEW', object)",
            security: "is_granted('ROLE_USER')",
            name: 'me'
        ),
        new \ApiPlatform\Metadata\Post(),
        new Put(security: "is_granted('USER_EDIT', object)"),
        new Delete(security: "is_granted('USER_DELETE', object)")
    ]
)]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(type: 'boolean')]
    private $isVerified = false;

    #[ORM\Column(length: 40)]
    #[Groups(['post:read'])]
    private ?string $DisplayName = null;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Post::class, orphanRemoval: true)]
    private Collection $posts;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Comment::class, orphanRemoval: true)]
    #[Groups(['post:read'])]
    private Collection $comments;

    public function __construct()
    {
        $this->posts = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getDisplayName(): ?string
    {
        return $this->DisplayName;
    }

    public function setDisplayName(string $DisplayName): self
    {
        $this->DisplayName = $DisplayName;

        return $this;
    }

    /**
     * @return Collection<int, Post>
     */
    public function getPosts(): Collection
    {
        return $this->posts;
    }

    public function addPost(Post $post): self
    {
        if (!$this->posts->contains($post)) {
            $this->posts->add($post);
            $post->setUser($this);
        }

        return $this;
    }

    public function removePost(Post $post): self
    {
        if ($this->posts->removeElement($post)) {
            // set the owning side to null (unless already changed)
            if ($post->getUser() === $this) {
                $post->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setUser($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getUser() === $this) {
                $comment->setUser(null);
            }
        }

        return $this;
    }
}

03-SYMFONY/actunews/src/Controller/Dashboard/DashboardController.php
<?php

namespace App\Controller\Dashboard;

use App\Repository\PostRepository;
use App\Repository\UserRepository;
use App\Repository\CommentRepository;
use App\Repository\CategoryRepository;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class DashboardController extends AbstractController
{
    #[IsGranted('ROLE_MODERATEUR')]
    #[Route('/admin', name: 'admin_home', methods: 'GET')]
    # https://localhost:8000/admin
    public function home(
        PostRepository $postRepository,
        CommentRepository $commentRepository
        //UserRepository $userRepository,
        //CategoryRepository $categoryRepository
        )
    {
        //$nbPosts = $postRepository->nbPosts();
        //$nbUsers = $userRepository->nbUsers();
        //$nbCategories = $categoryRepository->nbCategories();
        //$nbComments = $commentRepository->nbComments();
        
        $comments = $commentRepository->findBy([], ['createdAt' => 'DESC']);

        $counts = $postRepository->nbAllSubjects();
        //dd($counts);

        //dd($nbPosts);
        return $this->render('dashboard/dashboard.html.twig', [
            'nbPosts' => $counts[0]['nbposts'],
            'nbUsers' => $counts[0]['nbusers'],
            'nbCategories' => $counts[0]['nbcategories'],
            'nbComments' => $counts[0]['nbcomments'],
            'comments' => $comments,
        ]);
        //return $this->json(['username' => 'jane.doe']);
    }
}

03-SYMFONY/actunews/templates/dashboard/dashboard.html.twig
{% extends 'layout.html.twig' %}

{% block final_stylesheets %}
		<!-- DATA TABLE CSS -->
		<link href="{{ asset('spruha/assets/plugins/datatable/css/dataTables.bootstrap5.css') }}" rel="stylesheet" />
		<link href="{{ asset('spruha/assets/plugins/datatable/css/buttons.bootstrap5.min.css') }}"  rel="stylesheet">
		<link href="{{ asset('spruha/assets/plugins/datatable/css/responsive.bootstrap5.css') }}" rel="stylesheet" />
		<!-- Owl-carousel css-->
		<link href="{{ asset('spruha/assets/plugins/owl-carousel/owl.carousel.css') }}" rel="stylesheet" />
		<!-- Mutipleselect css-->
		<link rel="stylesheet" href="{{ asset('spruha/assets/plugins/multipleselect/multiple-select.css') }}">

{% endblock %}

{% block title %}Tableau de bord{% endblock %}
{% block module %}Admin{% endblock %}
{% block action %}Dashboard{% endblock %}

{% block content %}
	
	<!-- row opened -->
	<div class="row row-sm">
		<div class="owl-carousel  owl-theme">
			
			<div class="item">
				<div class="card custom-card">
					<div class="card-body">
						<div class="d-flex no-block align-items-center">
							<div>
								<span class="text-muted tx-13 mb-3">Nb Articles</span>
								<h3 class="m-0 mt-2">{{ nbPosts }}</h3>
							</div>
							<div class="ms-auto mt-auto">
								<img src="../assets/img/svgs/crypto-currencies/btc.svg" class="wd-30 hd-30 me-2" alt="">
							</div>
						</div>
					</div>
				</div>
			</div>
			
			<div class="item">
				<div class="card custom-card">
					<div class="card-body">
						<div class="d-flex no-block align-items-center">
							<div>
								<span class="text-muted tx-13 mb-3">Nb Utilisateurs</span>
								<h3 class="m-0 mt-2">{{ nbUsers }}</h3>
							</div>
							<div class="ms-auto mt-auto">
								<img src="../assets/img/svgs/crypto-currencies/eth.svg" class="wd-30 hd-30 me-2" alt="">
							</div>
						</div>
					</div>
				</div>
			</div>
			
			<div class="item">
				<div class="card custom-card">
					<div class="card-body">
						<div class="d-flex no-block align-items-center">
							<div>
								<span class="text-muted tx-13 mb-3">Nb Catégories</span>
								<h3 class="m-0 mt-2">{{ nbCategories }}</h3>
							</div>
							<div class="ms-auto mt-auto">
								<img src="../assets/img/svgs/crypto-currencies/xrp.svg" class="wd-30 hd-30 me-2" alt="">
							</div>
						</div>
					</div>
				</div>
			</div>

			<div class="item">
				<div class="card custom-card">
					<div class="card-body">
						<div class="d-flex no-block align-items-center">
							<div>
								<span class="text-muted tx-13 mb-3">Nb Commentaires</span>
								<h3 class="m-0 mt-2">{{ nbComments }}</h3>
							</div>
							<div class="ms-auto mt-auto">
								<img src="../assets/img/svgs/crypto-currencies/ltc.svg" class="wd-30 hd-30 me-2" alt="">
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- row closed -->

	<!-- Row -->
	<div class="row row-sm">
		<div class="col-lg-12">
			<div class="card custom-card">
				<div class="card-body">
					<!--
					<div>
						<h6 class="main-content-label mb-1">Responsive DataTable</h6>
						<p class="text-muted card-sub-title">Responsive is an extension for DataTables that resolves that problem by optimising the table's layout for different screen sizes through the dynamic insertion and removal of columns from the table.</p>
					</div>
					-->
					<div class="table-responsive">
						<table class="table table-bordered" id="example2">
							<thead>
								<tr>
									<th class="wd-20p">Actions</th>
									<th class="wd-20p">Date</th>
									<th class="wd-25p">Utilisateur</th>
									<th class="wd-20p">Article</th>
									<th class="wd-20p">Contenu</th>
								</tr>
							</thead>
							<tbody>

								{% for comment in comments %}
									<tr>
										<td>
											<a href="{{ path('admin_comment_delete', {id: comment.id}) }}" class="btn btn-primary btn-sm" onclick="return confirm('Etes-vous certain ?')">Supprimer</a>
										</td>
										<td>{{ comment.createdAt|date }}</td>
										<td>{{ comment.user.displayName }}</td>
										<td>{{ comment.post.title }}</td>
										<td>{{ comment.content }}</td>
									</tr>
								{% endfor %}

							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- End Row -->

{% endblock %}

{% block final_javascripts %}
	<!-- Internal Data Table js -->
	<script src="{{ asset('spruha/assets/plugins/datatable/js/jquery.dataTables.min.js') }}"></script>
	<script src="{{ asset('spruha/assets/plugins/datatable/js/dataTables.bootstrap5.js') }}"></script>
	<script src="{{ asset('spruha/assets/plugins/datatable/js/dataTables.buttons.min.js') }}"></script>
	<script src="{{ asset('spruha/assets/plugins/datatable/js/buttons.bootstrap5.min.js') }}"></script>
	<script src="{{ asset('spruha/assets/plugins/datatable/js/jszip.min.js') }}"></script>
	<script src="{{ asset('spruha/assets/plugins/datatable/pdfmake/pdfmake.min.js') }}"></script>
	<script src="{{ asset('spruha/assets/plugins/datatable/pdfmake/vfs_fonts.js') }}"></script>
	<script src="{{ asset('spruha/assets/plugins/datatable/js/buttons.html5.min.js') }}"></script>
	<script src="{{ asset('spruha/assets/plugins/datatable/js/buttons.print.min.js') }}"></script>
	<script src="{{ asset('spruha/assets/plugins/datatable/js/buttons.colVis.min.js') }}"></script>
	<script src="{{ asset('spruha/assets/plugins/datatable/dataTables.responsive.min.js') }}"></script>
	<script src="{{ asset('spruha/assets/plugins/datatable/responsive.bootstrap5.min.js') }}"></script>
	<script src="{{ asset('spruha/assets/js/table-data.js') }}"></script>
	<script src="{{ asset('spruha/assets/js/select2.js') }}"></script>
	

	<!-- Peity js-->
	<script src="{{ asset('spruha/assets/plugins/peity/jquery.peity.min.js') }}"></script>

	
	<!-- Owl Carousel js-->
		<script src="{{ asset('spruha/assets/plugins/owl-carousel/owl.carousel.js') }}"></script>


	<!-- Internal Dashboard js-->
	<script src="{{ asset('spruha/assets/js/crypto-dashboard.js') }}"></script>

<script>
/*
$(document).ready(function () {
    $('#example2').DataTable({
        order: [[1, 'desc']],
    });
});
*/
</script>


{% endblock %}